config/routes.rb
Scribe::Application.routes.draw do
  put '/posts/update' => 'posts#update'
  delete '/posts/delete' => 'posts#delete'
  put '/comments/update' => 'comments#update'
  delete '/comments/delete' => 'commentss#delete'

  root to: 'users#new'
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  post '/comments/vote' => 'comments#vote'

  resources :comments
  resources :sessions
  resources :users
  resources :posts do
    resources :comments do
      member { post :vote }
    end
  end

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id          :integer          not null, primary key
#  description :string(255)
#  user_id     :integer
#  post_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  attr_accessible :description

  has_reputation :votes, source: :user, aggregated_by: :sum


  validates :description, presence: true, allow_blank: false

  # def self.most_voted
  # find_with_reputation(:votes, :all, {:order => 'votes DESC'})
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    # @comments = Comment.all
    @comments = Comment.find_with_reputation(:votes, :all, {order: "votes desc"})
    # @comments = Comment.page(params[:votes]).per(20).most_voted

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end


  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render json: @comment }
    # end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])
    @post = Post.find(params[:post_id])
    @comment.post = @post
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def vote
    value = params[:type]  == "up" ? 1 : -1
    @comment = Comment.find(params[:id])
    @comment.increase_evaluation(:votes, value, current_user)
    puts @comment.reputations
    redirect_to :back, notice: "you voted!"
  end

  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    # respond_to do |format|
    #   format.html { redirect_to comments_url }
    #   format.json { head :no_content }
    # end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <%= comment.description %>
  <div class="voting-buttons">
    <div class="buttons-left">
      <%= pluralize comment.reputation_for(:votes).to_i, "vote" %>
    </div>
    <% if current_user && !current_user.voted_for?(comment) %>
    <div class="buttons-left">
      <%= button_to "up", vote_post_comment_path(comment, type: "up") %>
    </div>
    <div class="buttons-left">
      <%= button_to "down", vote_post_comment_path(comment, type: "down") %>
    </div>
  </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
     <%= f.label "In 200 characters or less describe the trending topic to someone who may not have heard what happened!" %><br>
    <%= f.text_field :description %>
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<% link_to "Home", posts_path %>

app/views/comments/new.html.erb
<h1><em>Scribe</em> the topic!</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>