config/routes.rb
Scribe::Application.routes.draw do
  put '/posts/update' => 'posts#update'
  delete '/posts/delete' => 'posts#delete'
  put '/comments/update' => 'comments#update'
  delete '/comments/delete' => 'commentss#delete'

  root to: 'users#new'
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  post '/comments/vote' => 'comments#vote'

  resources :comments
  resources :sessions
  resources :users
  resources :posts do
    resources :comments do
      member { post :vote }
    end
  end

end

app/models/post.rb
 # == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  topic      :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  attr_accessible :topic


  validates :topic, presence: true, allow_blank: false
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
   <!--  <div id="error_explanation"> -->
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
   <!--  </div> -->
  <% end %>

<!--   <div class="field"> -->
    <%#= f.label :topic %><br>
    <%= f.text_field :topic %>
<!--   </div>
  <div class="actions"> -->
    <%= f.submit "Create Topic" %>
<!--   </div> -->
<% end %>

app/views/posts/_post.html.erb
<h2> <%= post.topic %> </h2>
<p>
<%= post.comments %>
</p>


<p>
 <% post.comments.each do |c| %>
    <%= post.comments[0]["description"] %>
  <% end %>
</p>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if current_user %>
<h1>Step 1</h1>
<h3>Create or comment on trending topic that people are talking about</h3>


<%#= render partial: "post", collection: @posts %>

<%= link_to "Create A New Topic", new_post_path %>

<ul>
<% @posts.each do |post| %>
  <li><%= link_to post.topic, post %>, #comments: <%= link_to post.comments.count, post %></li>

  <em>

  </em>
<% end %>
</ul>

<% end %>

app/views/posts/new.html.erb
<h1>Step 2</h1>
<h3>Write that topic in the text box</h3>

<%= render 'form' %>



<%#= form_tag posts_show_path :method => 'post' do %>
<p>
<%#= text_field_tag :topic, params[:topic] %>
<%#= button_to "Post Topic"  %>
<%# end %>
</p>
<br>

app/views/posts/show.html.erb
<h2> Click "New Comment" to <em>Scribe</em> it</h2>


<%= link_to "New Comment", new_post_comment_path(@post) %>

<h3><%= @post.topic %></h3>

<%= render @post.comments %>