config/routes.rb
Scribe::Application.routes.draw do
  put '/posts/update' => 'posts#update'
  delete '/posts/delete' => 'posts#delete'
  put '/comments/update' => 'comments#update'
  delete '/comments/delete' => 'commentss#delete'

  root to: 'users#new'
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  post '/comments/vote' => 'comments#vote'

  resources :comments
  resources :sessions
  resources :users
  resources :posts do
    resources :comments do
      member { post :vote }
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


  helper_method :current_user
  # before_filter :check_session

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
   end

  # def check_session

  #   user = User.authenticate(params[:name], params[:password])
  #     if @current_user.nil?
  #     flash.now.alert = "Please sign in!"
  #     redirect_to '/log_in'
  #   else
  #     "Hi"
  #   end
  # end
  #   session[:user_id] = user.id
  #   if session[:user_id] != @current_user.id
  #     redirect to root_url, :notice => "Please sign in!"
  #   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
          <ul class="nav">
            <li class="brand"><em>Scribe</em> It - by describing a trending topic in 200 chars or less</li>
              <% if current_user.nil? %>
              <span class="badge">
                <li><%= link_to "Sign up", sign_up_path %></li>
              </span>
              <span class="badge">
                <li><%= link_to "Log in", log_in_path %></li>
              </span>
              <% else %>

              <% end %>
              <% if current_user %>
                <span class="badge">
                  <li>Logged in as <%= current_user.name %>.</li>
                  </span>
                <span class="badge">
                  <li><%= link_to "Log out", log_out_path %></li>
                </span>
              <% end %>
            </ul>
      </nav>
    </div>
   <div class="container">
</header>